### ISSUE TITLE
Code problems

### ISSUE THREAD

**Issue by zhu2014yi** [ohhhyeahhh/SiamCAR#12]
hi，请问这儿代码中计算locations为啥要加32
![image](https://user-images.githubusercontent.com/42707205/85374191-f8949480-b566-11ea-867d-bc9cd40f018e.png),不甚感激！

**Comment by twotwo2** [comment]
为了抵消gird产生的偏移。255*255的特征图根据步长8生成25*25的网格，中心点发生了偏移。

**Comment by zhu2014yi** [comment]
> 为了抵消gird产生的偏移。255_255的特征图根据步长8生成25_25的网格，中心点发生了偏移。

非常感谢
