### ISSUE TITLE
Can you provide the processed Youtube-BB dataset?

### ISSUE THREAD

**Issue by Bradyeyi** [ohhhyeahhh/SiamCAR#3]
pysot中提供的百度云链接失效了，我使用下载脚本下载Youtube数据集，导致我的代理被反爬虫机制封锁了。数据集无法下载。你可以提供你使用pysot处理后的Youtube-BB数据集吗？

**Comment by ohhhyeahhh** [comment]
> pysot中提供的百度云链接失效了，我使用下载脚本下载Youtube数据集，导致我的代理被反爬虫机制封锁了。数据集无法下载。你可以提供你使用pysot处理后的Youtube-BB数据集吗？

数据量太大了。如果需要，可以邮件探讨 :-)

**Comment by Bradyeyi** [comment]
你是使用pysot下的下载脚本下载的Youtube-BB数据集，后处理的吗？另外你的邮箱是？

**Comment by ohhhyeahhh** [comment]
> 你是使用pysot下的下载脚本下载的Youtube-BB数据集，后处理的吗？另外你的邮箱是？

通过官网提供的方式下载的。给你qq邮箱发了邮件，请查收
