### ISSUE TITLE
Alternative Pretrained Model Links

### ISSUE THREAD

**Issue by Hibero** [ohhhyeahhh/SiamCAR#30]
Baidu can be a bit difficult to download from. Is it possible to get alternative download locations such as Google Drive?

Thanks!

**Comment by ohhhyeahhh** [comment]
Hi, we have upload the trained model and the tracking results to google driver today. Please find the links in the readme file.

**Comment by Hibero** [comment]
Thanks! I really appreciate the quick turnaround!
