### ISSUE TITLE
test the GOT10K problems

### ISSUE THREAD

**Issue by tangchuanming1995** [ohhhyeahhh/SiamCAR#34]
hi,sir. 
when i test GOT10K with your  **SiamCAR-GOT.pth**,there is a error problem
`RuntimeError: Error(s) in loading state_dict for ModelBuilder:
	size mismatch for down.weight: copying a param with shape torch.Size([256, 768, 1, 1]) from checkpoint, the shape in current model is torch.Size([768, 256, 1, 1]).`

but i use the **model_general.pth** ,it`s ok to test it .
could u tell me how to solve it ? 
thanks advance~

**Comment by WangJun-ZJUT** [comment]
Hi, We have updated the code and model, please test on the new code and model.

**Comment by tangchuanming1995** [comment]
> Hi, We have updated the code and model, please test on the new code and model.

thanks.
