### ISSUE TITLE
The question about train.py

### ISSUE THREAD

**Issue by aaahuia** [ohhhyeahhh/SiamCAR#37]
Just like the question “训练的问题？”in github
Your answer is “This problem is usually caused by a wrong path. We suggest that you should check the path of datasets .”
Can you explain it in more detail？
Isn't the path of dataset fixed？
Thank you very much！

  File "G:\practice\SiamCAR-master\tools\train.py", line 320, in <module>
    main()

  File "G:\practice\SiamCAR-master\tools\train.py", line 315, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)

  File "G:\practice\SiamCAR-master\tools\train.py", line 175, in train
    for idx, data in enumerate(train_loader):

  File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)

  File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)

AttributeError: Traceback (most recent call last):
  File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "..\pysot\datasets\dataset.py", line 248, in __getitem__
    template_box = self._get_bbox(template_image, template[1])
  File "..\pysot\datasets\dataset.py", line 207, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by AstoncPou** [comment]
the same error

**Comment by bibixiuxiuxiu** [comment]
AttributeError: 'NoneType' object has no attribute 'shape' 请问这个问题怎么解决的

**Comment by huchenjie339** [comment]
@aaahuia @bibixiuxiuxiu @AstoncPou ;朋友，请问下，这个问题你们解决了嘛。我最近也遇到了相同的问题。也是AttributeError: 'NoneType' object has no attribute 'shape'问题，好像是数据集出现了error image，目前出现error image的数据集包括yt_bb数据集中的一张图片，还有det数据集中的两种图片（注：这几张图片都存在，而且没有命名错误）。但我不知道这个问题出现的原因所在，也不知道怎么解决。希望朋友能帮忙解决一下，谢谢。以下是我跑代码的时候具体报的错误：


error image: train_dataset/yt_bb/crop511/train0096/13/y1tLTudWgLk/000223.00.x.jpg
error image: train_dataset/det/crop511/a/n07714571_153/000000.00.x.jpg
Traceback (most recent call last):
  File "train.py", line 315, in <module>
error image: train_dataset/det/crop511/a/n02087046_3331/000000.00.x.jpg
    main()
  File "train.py", line 310, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "train.py", line 171, in train
    for idx, data in enumerate(train_loader):
  File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data1/huchenjie/SiamCAR-master/pysot/datasets/dataset.py", line 250, in __getitem__
    template_box = self._get_bbox(template_image, template[1])
  File "/data1/huchenjie/SiamCAR-master/pysot/datasets/dataset.py", line 209, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by huchenjie339** [comment]
终于解决了，不是数据集本身的问题。是路径出错了。
把config.py文件中的所有和数据集有关的路径（如：__C.DATASET.VID.ROOT = 'train_dataset/vid/crop511'  ）改为你自己的绝对路径就行了。

**Comment by H4Njx** [comment]
> 终于解决了，不是数据集本身的问题。是路径出错了。
> 把config.py文件中的所有和数据集有关的路径（如：__C.DATASET.VID.ROOT = 'train_dataset/vid/crop511' ）改为你自己的绝对路径就行了。
你好 我把除了youtube bb之外的数据集的地址都改成绝对路径了 但是VID的数据集中还是有类似错误 
其中两个是\crop511\c\ILSVRC2015_train_00081003/000448.00.x.jpg 和 \crop511\d\ILSVRC2015_train_01012000/000062.00.x.jpg 之前coco的数据集在整理的时候也出现过这种情况，但是重新做了一遍就好了 这个vid的一直不行，实验室没有固态 机械的4k性能好差 拷贝一个数据集要好久。哭

**Comment by H4Njx** [comment]
> @aaahuia @bibixiuxiuxiu @AstoncPou ;朋友，请问下，这个问题你们解决了嘛。我最近也遇到了相同的问题。也是AttributeError: 'NoneType' object has no attribute 'shape'问题，好像是数据集出现了error image，目前出现error image的数据集包括yt_bb数据集中的一张图片，还有det数据集中的两种图片（注：这几张图片都存在，而且没有命名错误）。但我不知道这个问题出现的原因所在，也不知道怎么解决。希望朋友能帮忙解决一下，谢谢。以下是我跑代码的时候具体报的错误：
> 
> error image: train_dataset/yt_bb/crop511/train0096/13/y1tLTudWgLk/000223.00.x.jpg
> error image: train_dataset/det/crop511/a/n07714571_153/000000.00.x.jpg
> Traceback (most recent call last):
> File "train.py", line 315, in
> error image: train_dataset/det/crop511/a/n02087046_3331/000000.00.x.jpg
> main()
> File "train.py", line 310, in main
> train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
> File "train.py", line 171, in train
> for idx, data in enumerate(train_loader):
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in **next**
> return self._process_data(data)
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> data.reraise()
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
> raise self.exc_type(msg)
> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/data1/huchenjie/SiamCAR-master/pysot/datasets/dataset.py", line 250, in **getitem**
> template_box = self._get_bbox(template_image, template[1])
> File "/data1/huchenjie/SiamCAR-master/pysot/datasets/dataset.py", line 209, in _get_bbox
> imh, imw = image.shape[:2]
> AttributeError: 'NoneType' object has no attribute 'shape'



> @aaahuia @bibixiuxiuxiu @AstoncPou ;朋友，请问下，这个问题你们解决了嘛。我最近也遇到了相同的问题。也是AttributeError: 'NoneType' object has no attribute 'shape'问题，好像是数据集出现了error image，目前出现error image的数据集包括yt_bb数据集中的一张图片，还有det数据集中的两种图片（注：这几张图片都存在，而且没有命名错误）。但我不知道这个问题出现的原因所在，也不知道怎么解决。希望朋友能帮忙解决一下，谢谢。以下是我跑代码的时候具体报的错误：
> 
> error image: train_dataset/yt_bb/crop511/train0096/13/y1tLTudWgLk/000223.00.x.jpg
> error image: train_dataset/det/crop511/a/n07714571_153/000000.00.x.jpg
> Traceback (most recent call last):
> File "train.py", line 315, in
> error image: train_dataset/det/crop511/a/n02087046_3331/000000.00.x.jpg
> main()
> File "train.py", line 310, in main
> train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
> File "train.py", line 171, in train
> for idx, data in enumerate(train_loader):
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in **next**
> return self._process_data(data)
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> data.reraise()
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
> raise self.exc_type(msg)
> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/huchenjie/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/data1/huchenjie/SiamCAR-master/pysot/datasets/dataset.py", line 250, in **getitem**
> template_box = self._get_bbox(template_image, template[1])
> File "/data1/huchenjie/SiamCAR-master/pysot/datasets/dataset.py", line 209, in _get_bbox
> imh, imw = image.shape[:2]
> AttributeError: 'NoneType' object has no attribute 'shape'

我出现过coco数据集的里面的照片出问题的 @huchenjie339  然后重新做了一次数据集就好了 现在vid的数据集又出了问题。。。不知道为什么明明文件都在 也没损坏 但是就是出现这个shape的问题

**Comment by huchenjie339** [comment]
@H4Njx 你把配置文件中的数据集路径都改成绝对路径试试，我之前遇到的也是你这种情况，通过这种办法最总解决了问题。

**Comment by chenqj97** [comment]
@huchenjie339 你好，请问，你有全部裁剪完的got-10k的数据集文件吗，数据集预处理时候，出现只有部分图片被裁剪生成x和z文件，大部分都没有被处理到，如果有完整裁剪完的数据集能发个百度云链接吗
