### ISSUE TITLE
GOT10k Results

### ISSUE THREAD

**Issue by bluoluo** [ohhhyeahhh/SiamCAR#5]
Thank you very much for your work, but the result after uploading from the `GOT10k0.6_0.04_0.1` file you provided is `0.552, 0.661, 0.348`, which is a bit different from the paper. What is going on? Can you provide `reports.json`?

**Comment by twotwo2** [comment]
Thank you for pointing our fault. Due to our negligence, it is difficult to find the corresponding results of the paper, so we tested again. The latest uploaded file contains reports.json for got10k, which is much similar to the results of paper.

**Comment by bluoluo** [comment]
Thank you very much for your reply.

**Comment by bluoluo** [comment]
> Thank you for pointing our fault. Due to our negligence, it is difficult to find the corresponding results of the paper, so we tested again. The latest uploaded file contains reports.json for got10k, which is much similar to the results of paper.

Hi, I have noticed that you have a comparison with `SiamRPN++`. Can you provide the test results of `SiamRPN++` on `GOT10k`?

**Comment by twotwo2** [comment]
Your email？

**Comment by bluoluo** [comment]
> Your email？

lambailuo@gmail.com
Thank you！

**Comment by DXZDXZ** [comment]
@twotwo2 
Could you also send me the test results of SiamRPN++ and ECO on GOT-10k?
My Email: 2058288578@qq.com

**Comment by hennnley** [comment]
@twotwo2 @DXZDXZ @bluoluo 

Could you please send me the raw results or .json report file of SiamRPN++ on GOT-10k as well?
My E-mail: sh86880681@gmail.com

Thanks in advance!
