### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by zhu2014yi** [ohhhyeahhh/SiamCAR#6]
请问为啥这边要加torch.exp
![image](https://user-images.githubusercontent.com/42707205/84481953-7c2dc600-acc9-11ea-8637-809225cac60a.png)

**Comment by twotwo2** [comment]
bbox_reg对应(l,r,t,b)，而(l,r,t,b)应该是正数，有其他问题可以结合我们的论文来理解

**Comment by zhu2014yi** [comment]
非常感谢
