### ISSUE TITLE
算法的泛化性？

### ISSUE THREAD

**Issue by FishInWave** [ohhhyeahhh/SiamCAR#60]
您好，我在目标跟踪方面是个新人。从Readme上没看出来要如何实施在自己的设备和数据集上，能否给一些建议呢？

**Comment by ohhhyeahhh** [comment]
> 您好，我在目标跟踪方面是个新人。从Readme上没看出来要如何实施在自己的设备和数据集上，能否给一些建议呢？

Please refer to the code in: ./tools/demo.py
