### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by zzzmm1** [ohhhyeahhh/SiamCAR#7]
Thanks for sharing your outstanding work！
Will you intend to provide pretrained SiamCAR models to help us get the tracking results？

**Comment by ohhhyeahhh** [comment]
Please find the pertained models in readme.

**Comment by zzzmm1** [comment]
I just find the pretrained backbone and no pretrained SiamCAR models

**Comment by ohhhyeahhh** [comment]
Find it in "2. test" -:)

**Comment by zzzmm1** [comment]
sorry  I missed it. 
Thanks a lot
