### ISSUE TITLE
raw results与论文里面的结果不一致

### ISSUE THREAD

**Issue by laisimiao** [ohhhyeahhh/SiamCAR#73]
论文里面的got10k: 0.569  github: 0.571 实测: 0.579
论文里面的lasot: 0.507  github: 0.516 实测: 0.516
论文里面的uav123: 0.614  github: 0.640 实测: 0.623

你好，请问能提供一下可以跑出论文里面那样点数的raw results吗？因为需要引用你的论文和结果来画图，谢谢。

**Comment by laisimiao** [comment]
请问有lasot的，上面这个百度网盘里面没有LaSOT的，谢谢了，手动捂脸

**Comment by Capricorn231** [comment]
不好意思，已经在上面的百度网盘链接里更新了
